### ISSUE TITLE
Installation tutorial

### ISSUE THREAD

**Issue by streato** [StratumPanel/Stratum-Panel#17]
Can you provide a simple installation tutorial (dependencies, nginx config...)

thanks :)

**Comment by ericwang401** [comment]
Unfortunately, one is not available right now because the project is not done.

You can try to install Docker from docker.com

1. Clone the project
2. CD into the project folder and clone `https://github.com/laradock/laradock.git`
3. CD into Laradock folder and `cp .env.example .env`
4. Modify the PHP_VERSION setting to `8.0` and save
5. Look for the MySQL credentials in the .env file
6. Copy the credentials and CD back to project root directory and `cp .env.example .env` and edit the database credentials
7. CD back into Laradock folder and run `docker-compose up -d nginx mysql`
8. In the same Laradock folder run `docker-compose exec workspace bash`
9. Run `composer i`
10. The panel should be operational
